spring:
  jpa:
      hibernate:
        ddl-auto: create
  application:
    name: product
  datasource:
    initialization-mode: always
    url: jdbc:mysql://localhost:3306/db_example
    username: root
    password: password

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  error:
    include-stacktrace: never 


